<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Название',
    'Code' => 'Код',
    'Category Name' => 'Название категории',
    'Translation Language' => 'Язык перевода',
    'Message' => 'Сообщение',
    'Translation' => 'Перевод',
    'Dictionary' => 'Словарь',
    'Hello!' => 'Здравствуйте!',
    'Home' => 'Главная',
    'Welcome!' => 'Добро пожаловать!',
    'Add Category' => 'Добавить категорию',
    'Add Entry' => 'Добавить запись',
    'Add Language' => 'Добавить язык',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Categories' => 'Категории',
    'Create' => 'Создать',
    'Create Category' => 'Создать категорию',
    'Create Dictionary' => 'Создать словарь',
    'Create Language' => 'Создать язык',
    'Delete' => 'Удалить',
    'Dictionaries' => 'Словари',
    'Dictionary entries' => 'Словарные записи',
    'Languages' => 'Языки',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить: ',
];
